FROM python:3.7-slim

RUN mkdir -p /opt/dagster/dagster_home /opt/dagster/app
RUN mkdir /opt/dagster/app/nhl_dagster
RUN mkdir /opt/dagster/app/nhl_dbt

COPY requirements.txt /opt/dagster/app
COPY nhl_dbt /opt/dagster/app/nhl_dbt/ 
COPY nhl_dagster /opt/dagster/app/nhl_dagster/
COPY workspace.yaml /opt/dagster/app/

ENV DAGSTER_HOME=/opt/dagster/dagster_home/

COPY dagster.yaml /opt/dagster/dagster_home/

WORKDIR /opt/dagster/app

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

ENV AWS_ACCESS_KEY_ID=AKIAZNPFTOMRZY4URRGB
ENV AWS_SECRET_ACCESS_KEY=X+pzKd5wfXuF+TPg0UVX+HYKML/8+ZF2j/BTrqsY

EXPOSE 4000

# CMD allows this to be overridden from run launchers or executors that want
# to run other commands against your repository
CMD ["dagster", "api", "grpc", "-h", "0.0.0.0", "-p", "4000", "-f", "nhl_dagster/repo.py"]