version: "3.7"

services:

  docker_user_code:
    build:
      context: .
      dockerfile: ./Dockerfile_user_code
    container_name: docker_user_code
    image: docker_user_code_image
    restart: always
    environment:
      DAGSTER_POSTGRES_USER: "postgres"
      DAGSTER_POSTGRES_PASSWORD: "postgres"
      DAGSTER_POSTGRES_DB: "dagster_nhl_db"
      DAGSTER_CURRENT_IMAGE: docker_user_code_image
    networks:
      - docker_network

  dagit:
    build:
      context: . 
      dockerfile: ./Dockerfile_dagster
    entrypoint:
      - dagit
      - -h 
      - "0.0.0.0"
      - -p 
      - "3000"
      - -w 
      - workspace.yaml
    container_name: docker_dagit
    expose:
      - "3000"
    ports:
      - "3000:3000"
    environment:
      DAGSTER_POSTGRES_USER: "postgres"
      DAGSTER_POSTGRES_PASSWORD: "postgres"
      DAGSTER_POSTGRES_DB: "dagster_nhl_db"
    volumes: # Make docker client accessible so we can terminate containers from dagit
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - docker_network
    depends_on:
      - docker_user_code

  docker_daemon:
    build:
      context: .
      dockerfile: ./Dockerfile_dagster
    entrypoint:
      - dagster-daemon
      - run
    container_name: docker_daemon
    restart: on-failure
    environment:
      DAGSTER_POSTGRES_USER: "postgres"
      DAGSTER_POSTGRES_PASSWORD: "postgres"
      DAGSTER_POSTGRES_DB: "dagster_nhl_db"
    volumes: # Make docker client accessible so we can launch containers using host docker
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - docker_network
    depends_on:
      - docker_user_code

networks:
  docker_network:
    driver: bridge
    name: docker_network