version: 2

sources:
  - name: NHL_DB_RAW
    database: NHL_DB
    schema: RAW
    tables:
      - name: RAW_NHL_GAME_DATA
      
models:
  - name: stg_game_events
    description: 1 row per unique game event.
    columns: 
      - name: play_id
        tests:
          - unique
          - not_null

  - name: stg_game_events_players
    description: Contains player and player type information regarding each play in a given game_id.

  - name: stg_game_officials
    desription: Contains linesman & officials for each game_id.

  - name: stg_player_demographics
    description: Contains player demograhpic data at the time of each game.