default:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: pua88554
      user:  flyers88
      password:  VampireWeekend2021
      role: ACCOUNTADMIN
      database: NHL_DB
      warehouse: NHL_ANALYTICS
      schema: DBT_ARYAN
      threads: 200