name: dbt_cd

on:
  push:
    branches:
      - main
      
# Get the schema created by the pull request. We'll want to delete this to clean up snowflake.
env:
  CI_SCHEMA: dbt_ci_${{github.event.pull_request.number}}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup Python 3
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      
      - name: Install dependencies
        run: | 
          pip install --upgrade pip
          pip install -r requirements.txt


      - name: Update dbt manifest in prod s3 bucket
        run: python nhl_dbt_cd/upload_manifest_to_s3.py --path nhl_dbt/target/manifest.json
        env:
          AWS_S3_BUCKET: nhl-prod-dbt-manifest
          AWS_ACCESS_KEY_ID: AKIAZNPFTOMRZY4URRGB
          AWS_SECRET_ACCESS_KEY: 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


      - name: Drop snowflake CI schema
        run: python nhl_dbt_cd/drop_snowflake_ci_schema.py
        env:
         SNOWFLAKE_USER: flyers88
         SNOWFLAKE_PASSWORD: VampireWeekend2021
         SNOWFLAKE_ACCOUNT: pua88554
         SNOWFLAKE_DB: NHL_DB
