# This is a basic workflow to help you get started with Actions
name: dbt_ci

on:
  pull_request:
    branches: [ main ]
    paths: 
    - 'nhl_dbt/**'

env:
  CI_SCHEMA: dbt_ci_${{github.event.pull_request.number}}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      #Downloads prod dbt manifest to compare agaist
      - name: Fetch prod dbt_manifest:
        run: python nhl_dbt_cd/download_manifest_from_s3.py

      #Compile generates new dbt manifest with app code 
      - name: dbt compile - generate new manifest
        run: cd nhl_dbt && dbt compile --profiles-dir .

      - name: dbt run modified models & their children
        run: cd nhl_dbt && dbt run --models state:modified+ --defer --state  ./ci_manifest --profiles-dir . --target ci

      - name: dbt test modified models & their children
        run: cd nhl_dbt && dbt test --models state:modified+ --defer --state  ./ci_manifest --profiles-dir . --target ci