name: dbt_cd

on:
  pull_request:
    branches:
      - main
    types:
      - closed
      
# Get the schema created by the pull request. We'll want to delete this to clean up snowflake.
env:
  CI_SCHEMA: dbt_ci_${{github.event.pull_request.number}}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  if_merged:
    if: github.event.pull_request.merged
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python 3
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      
      - name: Install dependencies
        run: | 
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Update dbt manifest in prod s3 bucket
        run: python3 nhl_dbt_cd/upload_manifest_to_s3.py --path nhl_dbt/target/manifest.json
        env:
          AWS_S3_BUCKET: nhl-prod-dbt-manifest
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


      - name: Drop snowflake CI schema
        run: python nhl_dbt_cd/drop_snowflake_ci_schema.py
        env:
         SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
         SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
         SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
         SNOWFLAKE_DB: NHL_DB

      - name: Execute dbt full-refresh of all models w/new
        run: cd nhl_dbt && dbt run --full-refresh --profiles-dir . --target prod