# This is a basic workflow to help you get started with Actions
name: dbt_ci_test

on:
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Pip install dbt
        run: pip install dbt-core dbt-snowflake

      - name: dbt check state modified
        run: cd nhl_dbt && dbt ls --models state:modified --state ./ci_manifest --profiles-dir . 